<div class="optimiseweb-system-config-fieldset-hint">

    <a target="_blank" href="<?php echo $this->getOptimiseWebUrl(); ?>"><img src="<?php echo $this->getPxUrl(); ?>" /></a>

    <h4>
        <strong style="color:#ea7601;"><?php echo $this->getModuleName(); ?> v<?php echo $this->getModuleVersion(); ?></strong> by <a target="_blank" href="<?php echo $this->getOptimiseWebUrl(); ?>"><strong>Optimise Web</strong></a>
    </h4>

    <h3>
        <a href="https://github.com/vkathirvel/Magento-Extension-Redirects/wiki" target="_blank" title="<?php echo $this->__('Click here for this module\'s configuration and usage documentation') ?>"><strong><?php echo $this->__('Click here for this module\'s configuration and usage documentation') ?></strong></a>
    </h3>

    <p>
        <a target="_blank" href="<?php echo $this->getOptimiseWebUrl(); ?>"><strong>Optimise Web</strong></a> <?php echo $this->__('is a <strong>Full Service Digital Agency</strong> from Edinburgh (Scotland, UK)') ?>.
        <?php echo $this->__('The author of this extension') ?>, <a target="_blank" href="<?php echo $this->getKathirVelUrl(); ?>"><strong>Kathir 'Sid' Vel</strong></a>, <?php echo $this->__('is our eCommerce and Digital Marketing specialist') ?>.
    </p>

    <p>
        <?php echo $this->__('Need assistance?') ?> <a target="_blank" href="<?php echo $this->getHelpDeskUrl(); ?>"><?php echo $this->__('Submit a ticket') ?></a>.
        <?php echo $this->__('Got feedback?') ?> <a target="_blank" href="<?php echo $this->getOptimiseWebEmailLink(); ?>"><?php echo $this->__('Email us') ?></a>.
        <!--Subscribe to our newsletter? <a target="_blank" href="<?php echo $this->getOptimiseWebUrl(); ?>">Visit our website</a>.-->
    </p>

</div>

<style>
    .optimiseweb-system-config-fieldset-hint  {
        background: #E7EFEF;
        border: 1px solid #CCCCCC;
        margin-bottom: 10px;
        padding: 11px 0 0 10px;
    }
</style>